New feature: styled strings
LuqueDaniel/vscode-language-renpy pull request #101
Opened 2022-04-28 07:19 UTC by JelleInfinity

* Added back escaped chars, placeholders and tags from previous version.
* Improved meta information
* Added special cases fro styled tags

2022-04-29 17:27 UTC, LuqueDaniel requested changes
Nice feature 👍 

* In some cases the [interpolating data](https://www.renpy.org/doc/html/text.html#interpolating-data) isn't displayed well.
  ![imagen](https://user-images.githubusercontent.com/1286535/165990391-e0e657dc-e460-411d-abc3-b9404715d80a.png)
* Is it intentional that tag attributes have the same style as strings?
  ![imagen](https://user-images.githubusercontent.com/1286535/165993018-d435373e-d09d-4b9b-a219-e28a93dd836e.png)

2022-04-29 21:08 UTC, JelleInfinity commented
Oh yes, that's a difficult one.. I think the following pattern should be reasonable:

![image](https://user-images.githubusercontent.com/60387522/166068613-2ea5b92c-71d3-472b-88ec-e4ddccd4c2b9.png)



### This also catches missing brackets:



![image](https://user-images.githubusercontent.com/60387522/166068647-ae559473-2c29-4f8c-a91e-4b499c9708f2.png)
![image](https://user-images.githubusercontent.com/60387522/166068681-875f39fb-b675-4de9-8b76-c31c89e23b4b.png)



### With the exception of recursive missing brackets, where it catches the outer bracket now:



![image](https://user-images.githubusercontent.com/60387522/166068735-b909f524-8855-49f8-8a51-127f933e10d5.png)

(Sorry about the large images)

2022-04-29 21:13 UTC, JelleInfinity commented
As for the attribute style, it currently has a meta tag that doesn't override the style. I wasn't sure what to use there yet, and I think I want to add cases for known tags (like size and color) to make sure it displays correctly. Maybe for now I set it to embedded python code?

2022-04-29 21:15 UTC, JelleInfinity commented
Also for know self-closing tags like image. The underline was kind of a debug style to notify me it was using the 'Start tag' fallback case

2022-04-30 11:04 UTC, JelleInfinity commented
I'm working on some additions. We can have colored text like this:
![image](https://user-images.githubusercontent.com/60387522/166102722-e1ada242-e985-4e09-b1cb-4710bb2e2a83.png)

But to make this available I need to make some modifications to the typescript parser, so it will take some time to add this.

I can also color the say statements with the character's color like that 😄

2022-04-30 12:39 UTC, LuqueDaniel commented
@JelleInfinity Wow interesting! Let me know when it's ready for review. Or should we merge first?

2022-05-01 08:30 UTC, JelleInfinity commented
Yeah I was already planning on adding that to the config. Also might need to think of some way to change the background color or something, in case someone has a color scheme that clashes with the vs code background color

2022-05-01 22:41 UTC, JelleInfinity commented
I'd suggest you do a quick review again. I think this is almost ready :D

I'll add the custom scope generation in a different pull request

2022-05-02 11:20 UTC, LuqueDaniel commented on syntaxes/renpy.tmLanguage_2.json
> +            "2": { "name": "entity.name.tag.$2.renpy" },
Interesting, I didn't know that this type of reference could be made. I like it!

2022-05-02 11:23 UTC, LuqueDaniel approved these changes
LGTM! 🎉 

@JelleInfinity  is ready to merge?

2022-05-02 11:49 UTC, JelleInfinity commented on syntaxes/renpy.tmLanguage_2.json
> +            "2": { "name": "entity.name.tag.$2.renpy" },
Yeah, I got that from looking at the html plugin in the vs code [repo](https://github.com/microsoft/vscode/blob/1cca784e1fcd5144e29b0ee7da7d6a0e5dd00b1b/extensions/html/syntaxes/html.tmLanguage.json)

2022-05-02 11:51 UTC, JelleInfinity commented
Yes, this is ready

2022-05-02 11:57 UTC, merged