fix: Allow double underscore in variable names
LuqueDaniel/vscode-language-renpy pull request #123
Opened 2022-05-21 19:47 UTC by JelleInfinity

* rxVariableCheck now allows the use of underscore in the name
* Added rxReservedVariableCheck that specifically tests for single underscore
* Added checkReservedRenpyNames function that pushes a warning if a single underscore variable was found
* Changed checkReservedPythonNames to result in a warning as the config suggests 'if (config.warnOnReservedVariableNames)'

2022-05-22 16:43 UTC, LuqueDaniel requested changes

2022-05-22 16:43 UTC, LuqueDaniel commented on src/diagnostics.ts
> +        const diagnostic = new Diagnostic(range, `"${matches[2]}" is a Python reserved name, type, or function. Using it as a variable can lead to obscure problems or unpredictable behavior.`, Diagno
Missing colon `:` after the variable reference (for consistency).

2022-05-22 16:43 UTC, LuqueDaniel commented on src/diagnostics.ts
> +    // check for default/define variables that are Python reserved names
That are Renpy reserved names.

2022-05-22 17:04 UTC, LuqueDaniel commented on CHANGELOG.md
> +- Properly remove the leading slash in file path [#98](https://github.com/LuqueDaniel/vscode-language-renpy/pull/98) (fix issue [#91](https://github.com/LuqueDaniel/vscode-language-renpy/issues/91))
Why replace or use asterisks with dashes?

2022-05-23 06:41 UTC, JelleInfinity commented on CHANGELOG.md
> +- Properly remove the leading slash in file path [#98](https://github.com/LuqueDaniel/vscode-language-renpy/pull/98) (fix issue [#91](https://github.com/LuqueDaniel/vscode-language-renpy/issues/91))
Prettier also auto formats .md files, apparently it dislikes * in favor of -. I disabled that on the other branch, but not here.

I will just add the config to this branch too so it doesn't touch these files.

2022-05-23 07:48 UTC, LuqueDaniel approved these changes
LGTM! 🎉

Thanks

2022-05-23 07:51 UTC, merged