added "Exclude Compiled Files From Workspace"
LuqueDaniel/vscode-language-renpy pull request #155
Opened 2022-07-02 16:01 UTC by KiloOscarSix

closes #148
Extended the "Exclude rpyc" option to include `.rpyc`, `.rpa`, `.rpymc` and `cache/`

Additional changes are due to ESLint forcing consistency
Actual changes are:
`package.json:91-95`
`src/extension.ts:41-56`
`src/extension.ts:354-361`

2022-07-02 18:29 UTC, LuqueDaniel commented
We shouldn't have two configuration options: `excludeRpycFilesFromWorkspace` and `excludeCompiledFilesFromWorkspace`. Especially since `excludeCompiledFilesFromWorkspace` also excludes `.rpyc` files. I think we should keep only the `excludeCompiledFilesFromWorkspace` option.

2022-07-02 18:50 UTC, KiloOscarSix commented
> We shouldn't have two configuration options: `excludeRpycFilesFromWorkspace` and `excludeCompiledFilesFromWorkspace`. Especially since `excludeCompiledFilesFromWorkspace` also excludes `.rpyc` files. I think we should keep only the `excludeCompiledFilesFromWorkspace` option.

Aye, I didn't want to be presumptuous and remove options, pushing a commit to remove "excludeRpyc" ...

2022-07-02 18:58 UTC, KiloOscarSix commented on src/extension.ts
> +				const newValue: boolean = workspace.getConfiguration("").get("conf.resource.insertEmptyLastLine") ?? true;
Shouldn't this be `workspace.getConfiguration("renpy").get("excludeCompiledFilesFromWorkspace")` instead of `conf.resource.insertEmptyLastLine` ?

2022-07-02 19:01 UTC, KiloOscarSix commented on src/extension.ts
> +				const newValue: boolean = workspace.getConfiguration("").get("conf.resource.insertEmptyLastLine") ?? true;
Resolved in #401b4e6

2022-07-05 21:30 UTC, LuqueDaniel approved these changes
LGTM! 🎉

2022-07-06 09:54 UTC, JelleInfinity commented
Hold up, the formatting used here is inconsistent with the formatting we use. We use prettier in this branch, please use that as it will also force spaces instead of tabs.

2022-07-06 10:33 UTC, JelleInfinity commented on src/extension.ts
> +				const newValue: boolean = workspace.getConfiguration("").get("conf.resource.insertEmptyLastLine") ?? true;
Yes, good catch :)

2022-07-06 10:39 UTC, JelleInfinity requested changes

2022-07-06 10:39 UTC, JelleInfinity commented on src/extension.ts
> +	if (fs.existsSync(jsonDumpFile)) {
You can remove this if statement and the variable above. It's pointless in this function :).

2022-07-06 10:39 UTC, JelleInfinity commented on src/extension.ts
> +	if (fs.existsSync(jsonDumpFile)) {
Not sure why it was still there in the first place. Must have missed it when I made the last modification

2022-07-07 07:00 UTC, KiloOscarSix commented
Merged main into PR
Ran Prettier

2022-07-07 08:23 UTC, JelleInfinity approved these changes

2022-07-07 08:23 UTC, merged