RunRenpyViaplugin
LuqueDaniel/vscode-language-renpy pull request #291
Opened 2023-04-12 13:24 UTC by seanj29

I don't have any expereince with typescript, so it may be a bit of a botched job, and I can't seem to get node.js to run on my machine, but this should be able to deal with https://github.com/LuqueDaniel/vscode-language-renpy/issues/115#issue-1239736338. I used a child process to run terminal command similar to what is done to watch for renpy compile data, but it should spawn a new renpy process in a new window.

2023-04-12 19:55 UTC, duckdoom4 commented
Hi there, thank your interest in the project and taking the time to build this PR. This is definitely a good start and the code looks good. (I will need to take some time later to test it before I accept).

That said, it would be nice if you can link this command to the 'play/run' button. That way we use the default behavior, instead of requiring users to run a command.

2023-04-12 20:10 UTC, duckdoom4 commented
I just looked through the documentation for this. I think the only way to do this, is through the debugger API.

https://code.visualstudio.com/api/extension-guides/debugger-extension

In our case, the full debugger is a bit of a stretch. But I think we should be able to use the mock debugger example they provided, then strip out all the debugger options and only provide the launch/run functionality.

Let me know if that's something you'd be willing to help with, or if you'd rather leave it as a command for now. Given that this is a bit more work, I totally understand if you do.

2023-04-12 20:23 UTC, duckdoom4 commented
Actually, looking at this: ![Screenshot_20230412-222052.jpg](https://user-images.githubusercontent.com/60387522/231575492-4e1b33e0-3907-4ecd-85d5-cdb7646453b4.jpg)

I think we might be able to add a launch configuration without the debugger. That would be best. In our case the 'type' should then be `cmd` instead of `mock`

2023-04-12 22:08 UTC, LuqueDaniel commented
Thank you very much for your contribution. I look forward to testing and reviewing it soon.

2023-04-14 19:56 UTC, duckdoom4 commented
I noticed that your formatting is configured to 2 spaces instead of four. Did you use prettier? The .editorconfig does use 4 spaces for ts files. Let me know if that setting doesn't work anymore

2023-04-15 21:33 UTC, seanj29 commented
Ill try rerunning it, I should have prettier installed on the machine tho gimme a sec

2023-04-15 21:40 UTC, seanj29 commented
Done now. Think my prettier for some reason didn't format the workspace on save like I set it to

2023-04-17 23:05 UTC, duckdoom4 commented
![Screenshot_20230418-010424.jpg](https://user-images.githubusercontent.com/60387522/232628726-ea64091d-6ccf-4dc4-b08a-0d24e49f6660.jpg)

That's much better, tho it's still applying two spaces instead of 4 :(

2023-04-18 07:00 UTC, seanj29 commented
I'll try to reformat again, should be able to whitespace diff instead of full diff instead, but hopefully this works.

2023-04-18 07:56 UTC, duckdoom4 commented
Yes perfect, that worked. I'll review it in a bit

2023-04-18 10:09 UTC, duckdoom4 requested changes
Awesome work! Looking really good, some minor things and then we can get this merged! 😄

2023-04-18 10:09 UTC, duckdoom4 commented on src/extension.ts
> +    if (isValidExecutable(renpy)) {
Remember that the config can be null, you should use the same check as above. 

(Even if you know you checked, if someone in the future wants to use this function, it should be safe to use on it's own)

2023-04-18 10:09 UTC, duckdoom4 commented on src/extension.ts
> +        let wf = getWorkspaceFolder();
I see now you copied it from the function below, so now worries. But my feedback should still be applied.

_I think this can be const. Also please use full (short) descriptive names for variables. If I want to know what `wf` means, I now have to look at the definition._

2023-04-18 11:53 UTC, seanj29 commented on src/extension.ts
> +                //this is kinda a hob botched together attempt that I'm like 30% certain has a chance of working
Did not manage to test if it works yet, will try after this commit

2023-04-18 11:54 UTC, seanj29 commented on src/extension.ts
> +            if (isValidExecutable(config.renpyExecutableLocation)) {
God it, fixed this now

2023-04-18 12:15 UTC, seanj29 commented
I can't seem to run the extension tests on my machine? Or at least the secondary checker one you have on there

2023-04-18 15:08 UTC, duckdoom4 requested changes

2023-04-18 15:08 UTC, duckdoom4 commented on src/extension.ts
> +    const renpy = config.renpyExecutableLocation;
This line will need to be inlined into the if. Else if config is null, this will throw an exception

2023-04-22 11:35 UTC, seanj29 commented
Also yeah, I did mean running the extension, I'm installing node.js now lmao, didn't even realize it was needed.

2023-05-07 19:43 UTC, duckdoom4 commented
Yes looking good. LGTM! 🎉🎉

2023-05-07 19:44 UTC, duckdoom4 approved these changes

2023-05-07 19:45 UTC, merged

2023-10-31 16:08 UTC, hsandt commented
Hey, I'm trying to use the command `Run: Renpy: Run Project` but it shows me an error:

> Ren'Py executable location not configured or is invalid.

I can see that it should be set in `config.renpyExecutableLocation` in the commit diff, but I see no such setting in Settings > Extensions > Ren'Py (there are only 10 settings, from editor.defaultFoldingRangeProvider to renpy.watchFoldersForChanges).

How am I supposed to set it?

2023-10-31 20:21 UTC, duckdoom4 commented
Hi there, I think there might be no UI entry for this (going off your comment). In that case you can only set it manually by adding this entry in the setting json config

2023-11-15 12:19 UTC, hsandt commented
> Hi there, I think there might be no UI entry for this (going off your comment). In that case you can only set it manually by adding this entry in the setting json config

So, the parameter is not autocompleted and not recognised (it appears half transparent and hovering it shows tooltip "Unknown Configuration Setting") but surprisingly setting it to the *full path* of renpy.sh (on Linux) actually replaces the "Ren'Py executable location not configured or is invalid." error bottom-right popup with a centered popup window:

![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/1067772/928d67fd-cb35-4885-bb25-9fc72e34f6e6)

Clicking on "Install cmd Extension" will suggest a few bash/command-related extension to install, but it doesn't seem quite right, so I'm not sure what to do now.

For now I just run Renpy via a custom command using [F5Anything](https://marketplace.visualstudio.com/items?itemName=discretegames.f5anything)...

2023-12-04 17:14 UTC, seanj29 commented
I've got some time, so I'm gonna try and remake this in better way, and try to get running working from GUI too.

2023-12-04 17:16 UTC, seanj29 commented
realised that its alredy been fixed in #115 oops