add debugger and task provider
LuqueDaniel/vscode-language-renpy pull request #360
Opened 2023-07-02 05:30 UTC by midgethetree

With these commits, users can use Run and Debug to run the current workspace in Ren'Py. This is now the default launch option for .rpy scripts when one is open in the active editor and there is no launch.json file setting a different default launch option. If the user chooses to generate a launch.json file for the current workspace, they can choose this debugger to get a launch.json file preconfigured to run that workspace in Ren'Py as the default launch option for the entire workspace.

These commits also provide four new tasks: lint, which lints the current workspace and saves it in lint.txt in the project folder; compile, which compiles the Ren'Py scripts in the current workspace; rmpersistent, which removes persistent data tied to the current workspace; and dialogue, which extracts dialogue from the current workspace in the default language.

Launch.json and tasks.json can be used to configure these new options and add additional launch options/tasks (to implement other renpy commands like translate, have multiple versions of the dialogue task using different arguments, have launch options with pretasks, etc.).

Finally, I fixed the existing run renpy command to utilize the new debugger instead of a "cmd" debugger users may not have an extension for. I also ensured the previously-used config option for setting the renpy executable's location actually appears as a setting in the vscode interface for editing, which is necessary for the debugger, tasks, and run command to work properly.

2023-07-02 08:43 UTC, duckdoom4 requested changes
Really awesome stuff! Thanks a lot for your contribution :)

Just one small question and then we can get this merged!

2023-07-02 08:43 UTC, duckdoom4 commented on package.json
> +    "workspaceContains:**/_ren.py",
Ah nice catch. I forgot to add this one :)

2023-07-02 08:43 UTC, duckdoom4 commented on src/extension.ts
> +    if (renpyTaskProvider) {
You can use the extension subscription register to automatically discard this.
`context.subscriptions.push(`

But I see you did do that in other places, so maybe there's a reason you didn't do it here?

2023-07-02 08:55 UTC, duckdoom4 commented
One more thing, could you swap the target branch to develop? 
We push new features to develop until we are certain nothing is broken. Then we merge develop back into master when we think everything is ready.

2023-07-02 22:02 UTC, midgethetree commented on src/extension.ts
> +    if (renpyTaskProvider) {
I was just copying that from the example task provider extension in the microsoft repo (https://github.com/microsoft/vscode-extension-samples/blob/main/task-provider-sample/src/extension.ts), but you're right that context.subscriptions should still work for this too, so I've changed that.

2023-07-03 06:40 UTC, duckdoom4 approved these changes
Awesome work, let get this merged! 🎉

2023-07-03 06:42 UTC, merged