[WIP] New Ren'Py grammar
LuqueDaniel/vscode-language-renpy pull request #76
Opened 2022-03-08 16:19 UTC by LuqueDaniel

Attempt to re-implement RenPy grammar.

### Done:
* Adds Ren'py comments and comments code tags Ej `TODO`, `FIXME`, etc
* Use the Python grammar in RenPy's Python statements (`python`, `init python`, `define` and `default`)

Although this PR is still in draft, any contribution to the `new-syntax` branch is welcome. **Feedback and testing are also appreciated**.

2022-03-18 17:48 UTC, multimokia requested changes
Small bugfix for init levels

2022-03-18 17:48 UTC, multimokia commented on syntaxes/renpy.tmLanguage_2.json
> +          "begin": "^(init\\s-?\\d?\\s?)?(python:)",
Only catches single digit init levels (`-9` to `9`) without any storemodules. This should fix that issue
Also catches `python early` too

```suggestion
          "begin": "^(init\\s-?\\d*\\s?)?(python(\\searly)?(\\sin\\s\\w+)?:)",
```

I'm not too sure how to make this highlight the storemodule name, init level, or `early` keyword

2022-03-18 18:34 UTC, multimokia requested changes
Added highlighting for the init level and the storemodule!

2022-03-18 18:34 UTC, multimokia commented on syntaxes/renpy.tmLanguage_2.json
> +        }
```suggestion
        },
        {
            "match": "(?<=init\\s)-?\\d+",
            "name": "constant.numeric"
        },
        {
            "match": "(?<=in\\s)\\w+",
            "name": "entity.name.namespace"
        }
```

2022-03-18 18:40 UTC, multimokia requested changes
To keep consistent with the current version, and to avoid ambiguity with `import` statements/control flow, I've pulled these back to `keyword.renpy`.

With all changes this looks like:
![image](https://user-images.githubusercontent.com/22531674/159064226-518fc39c-1bb2-4559-bdfe-7247b65d2ae9.png)
![image](https://user-images.githubusercontent.com/22531674/159064255-ae9c84f4-f909-42f9-bd92-8505692e640a.png)
![image](https://user-images.githubusercontent.com/22531674/159064295-02747c12-2b05-4f7d-af5d-c1175df3032d.png)

2022-03-18 18:40 UTC, multimokia commented on syntaxes/renpy.tmLanguage_2.json
> +        }
```suggestion
        {
          "match": "\\b(init|python|early|in)\\b",
          "name": "keyword.renpy"
        },
```

2022-03-18 18:56 UTC, LuqueDaniel commented on syntaxes/renpy.tmLanguage_2.json
> +          "begin": "^(init\\s-?\\d?\\s?)?(python:)",
I just realized another mistake of mine. This regular expression only matches when the `python` block is at the beginning of the line, i.e. there is no indentation. But if we fix it now the grammar won't know where a python block ends. We have to use the semantic token provider to know when a python block ends, based on its indentation.

2022-03-18 18:58 UTC, multimokia commented
Also wondering if it'll be possible to have the imported libraries be highlighted akin to Pylance's highlights:
![image](https://user-images.githubusercontent.com/22531674/159067467-2970bd90-7681-4e5d-ae76-51804e80c65c.png)

2022-03-18 19:09 UTC, LuqueDaniel commented on syntaxes/renpy.tmLanguage_2.json
> +        }
You are right, in fact, it's not a flow control keyword 😄

2022-03-18 19:20 UTC, multimokia commented on syntaxes/renpy.tmLanguage_2.json
> +          "begin": "^(init\\s-?\\d?\\s?)?(python:)",
You're right! If we do this semantically too, we may be able to fix breadcrumbs while we're at it. I've noticed the current code treats everything as 0 length scopes, so breadcrums never show because nothing is really in a scope, as all "scopes" have no length

2022-04-09 20:35 UTC, LuqueDaniel commented on syntaxes/renpy.tmLanguage_2.json
> +          "begin": "^(init\\s-?\\d?\\s?)?(python:)",
Can you test it again?

2022-05-27 21:11 UTC, multimokia commented
Noting an issue where a comment at the very start of the line will interrupt the tokenizer/syntax highlighter and interfere with the color
![image](https://user-images.githubusercontent.com/22531674/170789902-7cab0057-2d58-4f1b-b6f9-c46be31fed08.png)


Same block w/o the comment:
![image](https://user-images.githubusercontent.com/22531674/170790020-e5c5d67e-edbe-476d-8f41-4270c95a636d.png)

2022-05-28 09:28 UTC, JelleInfinity commented
> Noting an issue where a comment at the very start of the line will interrupt the tokenizer/syntax highlighter and interfere with the color ![image](https://user-images.githubusercontent.com/22531674/170789902-7cab0057-2d58-4f1b-b6f9-c46be31fed08.png)
> 
> Same block w/o the comment: ![image](https://user-images.githubusercontent.com/22531674/170790020-e5c5d67e-edbe-476d-8f41-4270c95a636d.png)

Ah that's interesting. That would be a bug for the build in python language syntax highlighter. That block is now embedded, so we don't do that part of the highlighter

2022-05-28 15:59 UTC, multimokia commented
![image](https://user-images.githubusercontent.com/22531674/170833158-b57aec29-ff24-46e2-8a37-de2019d242fc.png)
Using only stock VSCode python highlighting, this is the result, looks like it's fine here.

2022-05-28 19:49 UTC, JelleInfinity commented
Sorry I'm unable to look closely myself currently, otherwise I would have looked at it. There is a difference though, the whole block is indented one less in the example you provided last. I presume that could be why it doesn't show there

2022-05-28 19:56 UTC, JelleInfinity commented
Actually, seeing that it's possible the embedded block is cancelled after that comment. Could you press ctrl+alt+shift+i and show the scope of the incorrect line?

2022-05-28 20:22 UTC, multimokia commented
What action ctrl+alt+shift+i do? It doesn't seem to be bound to anything on my end

2022-05-28 20:33 UTC, JelleInfinity commented
Ah, that's supposed to be bound to Developer: Inspect TM Scopes.

You can find it through crtl+shift+P

2022-05-28 20:50 UTC, multimokia commented
Starting from the first one (where `len` would be highlighted: 
![image](https://user-images.githubusercontent.com/22531674/170842456-4006e4d2-0e5c-40ac-b6af-161141a1e11c.png)

Function definition line: 
![image](https://user-images.githubusercontent.com/22531674/170842464-08b53101-7e7a-4c8f-b0f1-0da65b99c1ce.png)

All carry `source.renpy`

2022-05-28 20:58 UTC, JelleInfinity commented
Language says Ren'Py though, so it is in fact cancelled. Thanks for the bug report! I will look into it later :)

2022-05-30 07:18 UTC, JelleInfinity commented
@multimokia I pushed a change that should fix this issue. Again, thanks for the report :)

2022-05-30 17:40 UTC, multimokia commented
Gonna give it a shot!

2022-05-31 17:02 UTC, JelleInfinity commented
@multimokia Turns out there was another bug is that pattern, where it wouldn't match if a block ended on the same line a new block started. Should be resolved with the latest push

2022-06-01 19:15 UTC, multimokia commented
Copying stuff over from Discord:

Screens don't have a highlight
![image](https://user-images.githubusercontent.com/22531674/171483269-694a4b45-d537-4dc3-8fba-287e0b342ab5.png)


Not all style properties have a highlight associated
![image](https://user-images.githubusercontent.com/22531674/171483318-2bf4f188-bd9a-4cd2-ada0-c2785022b46d.png)

Likewise, not all variables in styles are highlighted
![image](https://user-images.githubusercontent.com/22531674/171483383-b1029201-ce80-464e-ad65-40683947c94d.png)

Style definitions also don't properly highlight types:
booleans are non-colored
![image](https://user-images.githubusercontent.com/22531674/171483474-c0f8cebf-736d-40a4-872e-6f6694ec456c.png)

Functions don't have argument colors, nor parameter colors. Numbers also are not colored
![image](https://user-images.githubusercontent.com/22531674/171483507-14479a52-42ea-49f6-8ea7-d080334e8752.png)

Variable highlights are inconsistent in single-line python expressions vs python blocks:
![image](https://user-images.githubusercontent.com/22531674/171483932-4f97c5b0-10aa-4eca-9033-7b9fe1716fa5.png)

Image definitions have highlighting for the name as expected, however posess the same issues styles do in terms of definitions
![image](https://user-images.githubusercontent.com/22531674/171484243-0521692f-f8d5-4269-9680-72783b06f452.png)


Some nice to haves:
Consistent highlighting in dialogue interpolation (highlighted as variable in python, as well as inside the `[]`)
![image](https://user-images.githubusercontent.com/22531674/171483979-cb2d2865-3c87-4c18-b7e5-c8366d4b3e71.png)

Highlights of ideally all variables as it can get a little inconsistent (though this would probably be best with semantic tokenization)
![image](https://user-images.githubusercontent.com/22531674/171484083-6ea29ee1-a1b8-48ac-b0ad-030cdab1fc2a.png)

2022-06-02 06:45 UTC, JelleInfinity commented
@multimokia Thanks for the report. Those are known issues. The original syntax highlighter also had those issues.
In the next few days I'll work on getting those supported. 

- The style statement is quite a massive one, as this requires ATL support so it might take a while.
  * Booleans and other things are not highlighted because that is not considered python. Once the style statement is properly supported that should be fixed.
- The screen statement as well, because that also supports ATL. I can however make a quick change to make it support highlighting the function name.
- Image statement has the same issue; ATL is not properly supported currently

- Thanks for the missing style property, I'll add it now

- Variable highlighting will be fixed (in the future) in the updated semantic highlighter that will be part of a different pr. Since we would like to know if a variable exists before giving it the blue highlight I chose not to highlight those variable s with the syntax highlighter. Variables after $/define/default with an assignment are highlighted, because we know those exist.


Again, thanks for all the feedback you are a great help! I'm happy to see someone using the changes I've implemented so far :)

2022-06-05 01:08 UTC, multimokia commented
This makes sense! Thanks for the update, and I'm more than happy to test everything out for you as needed. The new changes have been a real help over on some of the projects I'm working on, which have a lot more going on than your traditional VN.

I'm really excited for the semantic tokenizer as that'll _really_ help with a lot.
That said, in the interest of the semantic tokenizer, it might be in better interest to remove the change I made to storemodules early in the PR and instead make those semantic tokens in that PR too? That way `store`s can properly be treated more akin to namespaces.

2022-06-06 11:45 UTC, JelleInfinity commented
@multimokia I'm thinking of building proper syntax highlighting support for all Ren'Py features before moving on to the semantic tokenizer. For now the PR can stay as is, once I get to that we can look into making the necessary changes. To give you a quick overview of what's left to do:

- [ ] Call/jump statments
- [ ] ATL (image, show, screen, style)
- [ ] with/hide/at/from clauses
- [ ] Say statments
- [ ] Window
- [ ] Camera/ Transform
- [ ] Audio (play, stop, queue, tags)
- [ ] Translate
- [ ] Creator-defined statements (See https://www.renpy.org/doc/html/cds.html)
- [ ] Reserved names

I think I might quickly go over each, make it feature complete and then try to improve each. But will see how it goes. Maybe I'll do it properly in one go.

2022-06-06 18:11 UTC, multimokia commented
Call/jump I think are high up for me, side from that, say statements, with/hide/at/from, and ATLs are next personally

2022-06-06 18:14 UTC, JelleInfinity commented
Ah, in that case, please give the call/jump statements which I've included in the last push a go. Would love to hear about any bugs/issues you come across.
I'll do say statements next then, but keep in mind this has limited functionality since it would only include syntax highlighting scopes

2022-06-06 21:11 UTC, multimokia commented
Looking at the example project too, this seems to occurr with single-line python statements too as after a point, the highlight fails:
![image](https://user-images.githubusercontent.com/22531674/172249979-e5bec74c-d621-44e9-bad2-22af75b1f338.png)

Note how `60` doesn't have standard number highlighting

2022-06-06 21:26 UTC, JelleInfinity commented
Okay, that should be fixed. Please have another look at the issues noted before. They might have all been fixed now :)

2022-06-06 22:41 UTC, multimokia commented
Gotcha! Makes sense, let me give it a go

2022-06-06 22:46 UTC, multimokia commented
Okay, I love the visual feedback of the bold/italics/underline text tags, that's a fantastic detail. At the moment, not seeing anything as an issue. If I may pose a suggestion or a nice to have, it'd be that expression codes could get their own highlight?

![image](https://user-images.githubusercontent.com/22531674/172261529-8dc4e98f-4a6c-424e-a796-07c23336df0e.png)
Since they're the same, it might be nice to have a differentiation in them, especially since characters are hard defined

2022-06-06 22:48 UTC, multimokia commented
Love the gold highlights for labels in call/jumps being consistent with their definitions, it's a nice touch. As well, good to see `call expression` doesn't continue the highlight

2022-06-07 05:38 UTC, JelleInfinity commented
@multimokia With "expression codes" are you referring to the say statements? Cus there is a pull request for highlighting the character definition and adding meta tags around the whole statement that includes the character name. (That way you make custom color rules for those. Eg. meta.say.narrator.renpy or meta.say.e.renpy)

2022-06-07 17:22 UTC, JelleInfinity commented
@multimokia Sounds cool. The commit has been merged so you can see if it fits your needs. 

To test out what it can do you can add the following to your /.vscode/settings.json file:
```
{
    "scope": "meta.say.narrator.renpy",
    "settings": {
        "foreground": "#ffffff"
    }
}
```

(Which I now realize is not in line with the custom tag scopes I defined before, so it will change)
In the future this scope will be added automatically like described before.

2022-06-07 17:31 UTC, multimokia commented
Awaiting the fix you described

2022-06-07 17:33 UTC, multimokia commented
> we fiddled with some renpy internals to allow on-the-fly sprite defintions according to our expression standard, if anything it might be handy to allow a pattern matcher or something in a settings json, but of course that's feature creep and pretty unlikely to be used outside of projects that use strictly defined expression systems

Mentioning this:
![image](https://user-images.githubusercontent.com/22531674/172446132-a5f7764c-5631-4927-80d1-c00fa19ebbff.png)
as an example
`3rksdlb`
`3` is pose number
`r` is looking right
`k` is knit brows
`sdl` is sweat-drop-left
`b` is big open smile

Being able to highlight the different regions of the sprite would be handy, but of course I don't know how feasible it is to "inject" a pattern matcher to link with colours, or if it's even worth doing lol, so it's more of a bit of musing unless this is actually something more people would use.

2022-06-07 19:10 UTC, JelleInfinity commented
> Awaiting the fix you described

Fix has been pushed. (Please note the modified scope arrangement to make it consistent with other custom token colors)

As for the second request; That would be out of my current scope. Though there is the [Creator-Defined Statements](https://www.renpy.org/doc/html/cds.html) thing that I want to look into supporting. Maybe you could use that feature in the future.

2022-06-07 19:16 UTC, multimokia commented
Ultimately creator defined statements wouldn't do what we need it to, but that's fine, the main developers of the project already understand what each part means, and since they're actual character expressions, a custom statement wouldn't cut the mustard (not to mention it'd involve changing a few ten thousand lines)

Regardless I understand it's out of the scope, it's a pretty niche request :)

2022-06-07 19:18 UTC, multimokia commented
I'm noticing some bugs:
![image](https://user-images.githubusercontent.com/22531674/172464264-5cc613aa-6a99-47e0-978b-b2fed44a4d13.png)

lines where expressions are specified don't have the highlight for characters, as well this breaks `return` statements

2022-06-07 19:19 UTC, JelleInfinity commented
> Ultimately creator defined statements wouldn't do what we need it to, but that's fine, the main developers of the project already understand what each part means, and since they're actual character expressions, a custom statement wouldn't cut the mustard (not to mention it'd involve changing a few ten thousand lines)
> 
> Regardless I understand it's out of the scope, it's a pretty niche request :)

Sorry for the misunderstanding, I was referring to the possibility of you being able to use the way it would be implemented to support your custom feature.

2022-06-07 19:19 UTC, multimokia commented
Ah no worries

2022-06-07 19:42 UTC, JelleInfinity commented
> I'm noticing some bugs: ![image](https://user-images.githubusercontent.com/22531674/172464264-5cc613aa-6a99-47e0-978b-b2fed44a4d13.png)
> 
> lines where expressions are specified don't have the highlight for characters, as well this breaks `return` statements

Ah yes, the return statement could also contain an expression of course. Nice catch, the priority of the say statements have been lowered to the correct place now

2022-06-07 20:04 UTC, multimokia commented
![image](https://user-images.githubusercontent.com/22531674/172471657-826844f6-6104-4236-88a5-662011f46b56.png)
Still seeing the same issue where lines with expressions dont have the character highlighted.

Additionally:
![image](https://user-images.githubusercontent.com/22531674/172471745-683a249b-366a-48a0-8996-e1a340aeb5ad.png)

Seems to resolve to `undefined`. It might be best to forego the auto description if the name cannot be resolved.

2022-06-07 20:14 UTC, JelleInfinity commented
>  Still seeing the same issue where lines with expressions dont have the character highlighted.
> 
> Additionally: 
> Seems to resolve to `undefined`. It might be best to forego the auto description if the name cannot be resolved.

Ah yes, I now see what the issue is with that specific line. Your character tags start with a number, which would (as far as I know) normally not be allowed since they would be variables. Tho, I will fix it in a way that allows your tags to sort of work.


Hmm, the undefined thing is new. Will look into that, maybe I broke something.. Curious thing is that it didn't appear at all on the main branch.

2022-06-07 20:35 UTC, multimokia commented
Images aren't "true" variables, they can't be accessed as identifiers, but they're references to internal entries in the `renpy.display.image.images` dict, if I recall correctly, the key/value mapping is `(characterName, say, attributes, here): Displayable`

In the case of the expressions you see there, `("monika", "1eka"): Displayable`, ironically _technically_ expressions can even have symbols in them, but you'd have to define them in a very unorthodox manner. But yeah, pretty much all characters are acceptable. With best assumtion is anything but symbols I'd say

2022-06-07 20:38 UTC, multimokia commented
![image](https://user-images.githubusercontent.com/22531674/172477899-f670e913-f8dd-4f28-a274-2e4396a14cfa.png)
I think `extend` should remain the same color as labels/other keywords, the vibrant blue implies it's a constant variable when it's not

2022-06-07 20:39 UTC, multimokia commented
Seems more than fine to me

2022-06-07 20:41 UTC, JelleInfinity commented
> I think `extend` should remain the same color as labels/other keywords, the vibrant blue implies it's a constant variable when it's not

Following the [documentation](https://www.renpy.org/doc/html/dialogue.html#special-characters) these characters are pre-defined characters. I suppose they are const no?

2022-06-07 20:41 UTC, multimokia commented
Nono, `extend` isn't a character, it's a keyword to continue the following text as the same character from the last line spoken

2022-06-07 20:45 UTC, JelleInfinity commented
> Nono, `extend` isn't a character (logically), it's a keyword to continue the following text as the same character from the last line spoken

Right, I agree it would make more sense to mark it as a keyword instead. Let's get that fixed then

2022-06-07 20:49 UTC, multimokia commented
Also I'm noticing text tags lost their effects, was the extension writing to the local settings json? I noticed it had some changes which overrode my global configs that added bolds, so I removed them

2022-06-07 20:53 UTC, JelleInfinity commented
The extension writes to /.vscode/settings.json into `editor.tokenColorCustomizations": { "textMateRules" }`

Though it should not overwrite any existing code. Plus it should add any missing effects automatically now. (I did push a fix for that earlier today)

2022-06-07 22:42 UTC, multimokia commented
Looks like that works! Nice to see it adapt from my global settings too (I have global textmate scope modifications so they apply to all languages)

2022-06-08 01:58 UTC, multimokia commented
Oh actually caught a bug

![image](https://user-images.githubusercontent.com/22531674/172514873-95eec7ac-2b48-41a7-b689-949356848ffb.png)
If the line ends with a comment, the next line thinks the quote is still going

2022-06-14 17:58 UTC, JelleInfinity commented
Thanks for letting me know! I'll see what I can do.
I've just started with a new fulltime assignment for the next half a year, so I won't have much time. 
I'll try to make some time in the weekends and maybe after work hours, but I won't be able to do as much as I did before.

2022-06-14 17:59 UTC, multimokia commented
No worries, it's open source, so any and all contribution is appreciated. The fact you've done so much already is deeply appreciated!

2022-06-19 21:41 UTC, JelleInfinity commented
@multimokia Hi mate, I took 30 minutes to quickly get those in. The code isn't super optimal, but this works for now. Let me know if you come across any other issues

2022-06-20 00:08 UTC, multimokia commented
those keywords seem to work nicely!

2022-06-20 21:14 UTC, JelleInfinity commented
Hi @multimokia and @LuqueDaniel, I modfied the say scopes a bit. I think this way it's more usefull.

![image](https://user-images.githubusercontent.com/60387522/174678446-9d43d576-c757-438a-8018-c64dff8b43fa.png)

2022-06-20 23:03 UTC, LuqueDaniel commented
I like the idea, it gives the user more options. 👍

2022-06-25 20:49 UTC, JelleInfinity commented
3 big one's left, then we are feature complete :D

2022-07-09 17:28 UTC, multimokia commented
Oh I caught a bug in the renpy `if` handling. If an `if`'s condition spans multiple lines, syntax highlighting fails for it.
![image](https://user-images.githubusercontent.com/22531674/178116487-028f5f93-630a-4cdb-aed1-7e0fe119ed0a.png)
![image](https://user-images.githubusercontent.com/22531674/178116502-5c276c1c-2c6e-4bf8-a537-c663feec7ebb.png)
![image](https://user-images.githubusercontent.com/22531674/178116522-043fb123-61c4-4866-94bf-50d6d6705a01.png)

Note that this only applies to renpy code and not embedded python

2022-07-10 13:01 UTC, JelleInfinity commented
Should be fixed now :)

2022-07-10 13:14 UTC, LuqueDaniel commented
On Monday I want to release the first pre-release of 2.2 (2.1 pre-release), so it will be easier to test for anyone interested.

2022-07-11 16:58 UTC, multimokia commented
Awesome!

2022-07-16 16:06 UTC, multimokia commented
![image](https://user-images.githubusercontent.com/22531674/179362738-c0678399-2998-4bb5-87ab-aa212c97aa6d.png)
Caught a bug in the syntax where if you concatenate strings with text tags, the inner variables are colored as strings and not as variables.

![image](https://user-images.githubusercontent.com/22531674/179362783-6273a17b-ec4b-44ea-8a36-c32f4b94fb75.png)

This also applies in python blocks

2022-07-16 19:52 UTC, JelleInfinity commented
Hi @multimokia. Thanks for yet another bug report! Since this is now live as pre release I would prefer if you make this an official issue ticket. 
That makes it easier to keep track of and prevents others from double posting an issue.
In there you will also find a bug report template for syntax bugs, it would be helpful if you could fill that out. In there we request a source sample and some additional screenshots with the scope inspector enabled.
Thanks in advance :)

2022-07-16 20:54 UTC, multimokia commented
Can do!

2022-07-17 22:22 UTC, LuqueDaniel commented
🤔 Maybe I should create a `develop` branch and merge this PR there.

2022-07-18 09:06 UTC, JelleInfinity commented
> 🤔 Maybe I should create a `develop` branch and merge this PR there.

We could simply rename this branch. But a `develop` branch would be a good idea.

2022-07-18 23:19 UTC, closed without merging

2022-07-18 23:22 UTC, LuqueDaniel commented
Done! I have renamed the branch to `develop`. You will need to update your local repository.